version: '3.8'
services:
  nestjs-estore-app:
    container_name: nestjs-estore-app
    image: amirtheahmed/nestjs-estore:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nestjs-estore-app.rule=Host(`nestjs-estore.amirtheahmed.dev`)"
      - "traefik.http.routers.nestjs-estore-app.entrypoints=https"
      - "traefik.http.services.nestjs-estore-app.loadbalancer.server.port=3002"
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "3002:3000"
    networks:
      - nestjs-estore
    depends_on:
      - nestjs-estore-db
    restart: unless-stopped

  nestjs-estore-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: estore-prod
    volumes:
      - nestjs-estore-db-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - nestjs-estore
    restart: unless-stopped

networks:
  nestjs-estore:

volumes:
  nestjs-estore-db-data:
