version: '3.8'
services:
  app:
    image: amirtheahmed/nestjs-estore:latest
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "3002:3000"
    networks:
      - nestjs-estore
    depends_on:
      - prod-db
    restart: unless-stopped

  prod-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: estore-prod
    volumes:
      - prod-db-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - nestjs-estore
    restart: unless-stopped

networks:
  nestjs-estore:

volumes:
  prod-db-data:
