export enum RoleSlug {
  ADMIN = 'admin',
  USER = 'user',
}

export const GET_CATEGORIES_CACHE_KEY = 'GET_CATEGORIES_CACHE';
export const GET_CHILD_CATEGORIES_CACHE_KEY = 'GET_CHILD_CATEGORIES_CACHE';
export const GET_PRODUCTS_CACHE_KEY = 'GET_PRODUCTS_CACHE';
