name: E-store | CI / CD

on:
  release:
    types: [created]

jobs:
  build-and-test:
    name: 🐳 Build Docker image and run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21'
      - name: Cache Node modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install Dependencies
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Run E2E tests
        run: npm run test:e2e
      - name: Build
        run: npm run build

  deploy:
    name: 🐳 Deploys Docker image to server
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            amirtheahmed/nestjs-estore:latest
            amirtheahmed/nestjs-estore:${{ github.ref_name }}
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            docker pull amirtheahmed/nestjs-estore:latest
            cd /home/amirtheahmed/apps/nestjs-estore &&
            git pull &&
            docker-compose -f docker-compose.prod.yaml pull &&
            docker-compose -f docker-compose.prod.yaml down &&
            docker-compose -f docker-compose.prod.yaml up -d 
